export const CREATE_TASK = 'CREATE_TASK';
export const INITIALIZE = 'INITIALIZE';
export const INITIALIZED = 'INITIALIZED';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
